"""обновил тип колонки с datetime на int

Revision ID: 75cdbc6d0d63
Revises: 526b2835b72e
Create Date: 2026-03-24 15:08:48.085668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cdbc6d0d63'
down_revision: Union[str, Sequence[str], None] = '526b2835b72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
