"""обновил тип колонки с int на date

Revision ID: f042caf058bc
Revises: 75cdbc6d0d63
Create Date: 2026-03-24 15:55:13.179504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f042caf058bc'
down_revision: Union[str, Sequence[str], None] = '75cdbc6d0d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('biographies_users', 'year_of_birth',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using="make_date(year_of_birth, 1, 1)",
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('biographies_users', 'year_of_birth',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="extract(year from year_of_birth)::integer",
               )
    # ### end Alembic commands ###
